"use client";

/**Shared Slurm parameter fields + start command card, used in settings and run modal.*/

import { useState, useCallback, useEffect, useRef } from "react";
import CodeTextarea from "@/components/ui/CodeTextarea";

export interface SlurmFields {
  partition: string;
  cpus: string;
  memory: string;
  gpu_gres: string;
  work_dir: string;
  time: string;
}

export const EMPTY_SLURM: SlurmFields = {
  partition: "",
  cpus: "",
  memory: "",
  gpu_gres: "",
  work_dir: "",
  time: "",
};

/** Strip shell metacharacters from a Slurm field value. */
function sanitize(v: string): string {
  return v.replace(/[;|&$`'"\\(){}<>!\n\r]/g, "");
}

export function buildSlurmCmd(s: SlurmFields): string {
  const gpu = sanitize(s.gpu_gres.trim());
  const gres = gpu ? ` --gres=gpu:${gpu}` : "";
  const nv = gpu ? " --nv" : "";
  const partition = sanitize(s.partition.trim()) || "PARTITION";
  const cpus = sanitize(s.cpus.trim()) || "CPUS";
  const mem = sanitize(s.memory.trim()) || "MEMORY";
  const workDir = sanitize(s.work_dir.trim()) || "WORK_DIR";
  const time = sanitize(s.time.trim()) || "TIME";
  return (
    `source /etc/profile && module load apptainer && ` +
    `srun --job-name=autofyn -p ${partition} -n 1 --cpus-per-task=${cpus} --mem=${mem} --time=${time}${gres} ` +
    `bash -c 'W=${workDir}/autofyn/runs/$AF_RUN_KEY && mkdir -p $W && ` +
    `apptainer exec${nv} --overlay $W --pwd /opt/autofyn -B $HOME $AF_HOST_MOUNTS ${workDir}/autofyn/sandbox.sif python3 -m server; rm -rf $W'`
  );
}

const PLACEHOLDERS = new Set(["PARTITION", "CPUS", "MEMORY", "WORK_DIR", "TIME"]);

/** Strip placeholder values generated by buildSlurmCmd for empty fields. */
function stripPlaceholder(v: string): string {
  return PLACEHOLDERS.has(v) ? "" : v;
}

export function parseSlurmCmd(cmd: string): SlurmFields | null {
  if (!cmd.includes("srun") || !cmd.includes("apptainer")) return null;
  const partition = stripPlaceholder(cmd.match(/-p\s+(\S+)/)?.[1] ?? "");
  const cpus = stripPlaceholder(cmd.match(/--cpus-per-task=(\S+)/)?.[1] ?? "");
  const memory = stripPlaceholder(cmd.match(/--mem=(\S+)/)?.[1] ?? "");
  const gresMatch = cmd.match(/--gres=gpu:(\S+)/);
  const gpu_gres = gresMatch?.[1] ?? "";
  const timeMatch = cmd.match(/--time=(\S+?)(?:\s|$)/);
  const time = stripPlaceholder(timeMatch?.[1] ?? "");
  const workDirMatch = cmd.match(/W=(\S+?)\/autofyn\/runs/);
  const work_dir = stripPlaceholder(workDirMatch?.[1] ?? "");
  return { partition, cpus, memory, gpu_gres, work_dir, time };
}

const INPUT_CLASS =
  "w-full bg-black/30 border border-border rounded px-2.5 py-1.5 text-content font-mono text-accent-hover placeholder:text-text-secondary focus-visible:outline-none focus-visible:border-[#00ff88]/30";

function FieldLabel(props: {
  label: string;
  hint?: string;
  required?: boolean;
  children: React.ReactNode;
}): React.ReactElement {
  return (
    <div>
      <label className="text-content uppercase tracking-[0.15em] text-text-muted font-semibold mb-1 block">
        {props.label}
        {props.required && <span className="text-[#ff4444] ml-0.5">*</span>}
        {props.hint && <span className="normal-case tracking-normal font-normal text-text-dim ml-1.5">{props.hint}</span>}
      </label>
      {props.children}
    </div>
  );
}

const REQUIRED_SLURM_KEYS: readonly (keyof SlurmFields)[] = [
  "partition", "work_dir", "cpus", "memory", "time",
];

export function isSlurmValid(fields: SlurmFields): boolean {
  return REQUIRED_SLURM_KEYS.every((k) => fields[k].trim() !== "");
}

interface SlurmFieldsCardProps {
  startCmd: string;
  onStartCmdChange: (cmd: string) => void;
  onWorkDirChange?: (workDir: string) => void;
  onValidChange?: (valid: boolean) => void;
}

export function SlurmFieldsCard({
  startCmd,
  onStartCmdChange,
  onWorkDirChange,
  onValidChange,
}: SlurmFieldsCardProps): React.ReactElement {
  const initialSlurm = startCmd
    ? parseSlurmCmd(startCmd) ?? EMPTY_SLURM
    : EMPTY_SLURM;
  const [slurm, setSlurm] = useState<SlurmFields>(initialSlurm);
  const internalChangeRef = useRef(false);

  // Use a ref to read the latest slurm state synchronously after setSlurm,
  // so external callbacks are called outside the React state updater.
  const slurmRef = useRef(initialSlurm);

  // Emit initial validity on mount.
  useEffect(() => {
    onValidChange?.(isSlurmValid(initialSlurm));
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);

  const updateSlurm = useCallback((patch: Partial<SlurmFields>): void => {
    setSlurm((prev) => {
      const next = { ...prev, ...patch };
      slurmRef.current = next;
      return next;
    });
    const next = slurmRef.current;
    const cmd = buildSlurmCmd(next);
    internalChangeRef.current = true;
    onStartCmdChange(cmd);
    onValidChange?.(isSlurmValid(next));
    if (patch.work_dir !== undefined && onWorkDirChange) {
      onWorkDirChange(next.work_dir);
    }
  }, [onStartCmdChange, onWorkDirChange, onValidChange]);

  // Sync textarea-to-fields: when startCmd changes externally (i.e. NOT from
  // updateSlurm), parse it and update structured fields.
  useEffect(() => {
    if (internalChangeRef.current) {
      internalChangeRef.current = false;
      return;
    }
    const parsed = startCmd ? parseSlurmCmd(startCmd) : null;
    if (parsed) {
      setSlurm(parsed);
      onValidChange?.(isSlurmValid(parsed));
    }
  }, [startCmd, onValidChange]);

  return (
    <div className="space-y-3">
      <div className="grid grid-cols-3 gap-3">
        <FieldLabel label="Partition" required>
          <input
            type="text"
            value={slurm.partition}
            onChange={(e) => updateSlurm({ partition: e.target.value })}
            placeholder="gpu, normal, etc."
            className={INPUT_CLASS}
          />
        </FieldLabel>
        <FieldLabel label="Work Directory" required>
          <input
            type="text"
            value={slurm.work_dir}
            onChange={(e) => updateSlurm({ work_dir: e.target.value })}
            placeholder="~/scratch"
            className={INPUT_CLASS}
          />
        </FieldLabel>
        <FieldLabel label="Time" required hint="(HH:MM:SS)">
          <input
            type="text"
            value={slurm.time}
            onChange={(e) => updateSlurm({ time: e.target.value })}
            placeholder="4:00:00"
            className={INPUT_CLASS}
          />
        </FieldLabel>
      </div>
      <div className="grid grid-cols-3 gap-3">
        <FieldLabel label="CPUs" required>
          <input
            type="text"
            value={slurm.cpus}
            onChange={(e) => updateSlurm({ cpus: e.target.value })}
            placeholder="4"
            className={INPUT_CLASS}
          />
        </FieldLabel>
        <FieldLabel label="Memory" required>
          <input
            type="text"
            value={slurm.memory}
            onChange={(e) => updateSlurm({ memory: e.target.value })}
            placeholder="16G"
            className={INPUT_CLASS}
          />
        </FieldLabel>
        <FieldLabel label="GPU" hint="(optional)">
          <input
            type="text"
            value={slurm.gpu_gres}
            onChange={(e) => updateSlurm({ gpu_gres: e.target.value })}
            placeholder="a100:2"
            className={INPUT_CLASS}
          />
        </FieldLabel>
      </div>
      <FieldLabel label="Start Command" hint="(auto-generated)">
        <CodeTextarea
          value={startCmd}
          onChange={onStartCmdChange}
          placeholder=""
          rows={5}
        />
      </FieldLabel>
    </div>
  );
}
